export const USER_STATE_CHANGE = 'USER_STATE_CHANGE'
export const REMOVE_POST_FROM_UI = 'REMOVE_POST_FROM_UI'
export const CURRENT_USER_POSTS_UPDATE = 'CURRENT_USER_POSTS_UPDATE'

export const REPORT_MODAL_OPEN = 'REPORT_MODAL_OPEN'

export const CLEAR_MODAL = 'CLEAR_MODAL'

export const REMOVE_POSTID_FROM_REDUX = 'REMOVE_POSTID_FROM_REDUX'

export const BLOCK_USER_MODAL = 'BLOCK_USER_MODAL'

export const CLEAR_BLOCK_MODAL = 'CLEAR_BLOCK_MODAL'

export const REMOVE_BLOCK_USER_LOADED_POST = 'REMOVE_BLOCK_USER_LOADED_POST'

export const REMOVE_BLOCK_USERS_FROM_REDUX = 'REMOVE_BLOCK_USERS_FROM_REDUX'


export const INTIAL_VIEW_POST = 'INTIAL_VIEW_POST'

export const CLEAR_INTIAL_VIEW_POST = 'CLEAR_INTIAL_VIEW_POST'

export const CREATE_TOKEN = 'CREATE_TOKEN'

export const USER_CITY_CHANGE = 'USER_CITY_CHANGE'

export const SET_OPEN_STATE = 'SET_OPEN_STATE'

export const INTIAL_POST = 'INTIAL_POST'

export const ACTIVE_FEED_STATE = 'ACTIVE_FEED_STATE'
